name: Feature request
description: Suggest an improvement to fsweep
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the idea. Please describe the problem first, then the proposed change.
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What workflow is painful today?
      placeholder: I want to be able to...
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the behavior you'd like.
      placeholder: fsweep should...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches or workarounds?
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Include examples, references, or mock outputs.
    validations:
      required: false

